#
# Makefile generated by:
# codebench 0.55
#
# Project: Earmark
#
# Created on: 13-01-2021 16:59:22
#
#

###################################################################
##
##////  Objects
##
###################################################################

BUILD = debug

NAME = earmark

VPATH = src md4c/src

SRCS = \
	amimd.c \
	byte_buffer.c \
	editor_gadget.c \
	gui.c \
	hyperlink_editor.c \
	image_editor.c \
	json_util.c \
	md_to_html.c \
	prefs.c \
	search_gadget.c \
	settings_gadget.c \
	string_utils.c \
	table_editor.c \
	entity.c \
	md4c.c \
	md4c-html.c \
	
DIR_OBJS = build/$(BUILD)



OBJS = $(patsubst %.c, $(DIR_OBJS)/%.o, $(SRCS))


###################################################################
##
##////  Variables and Environment
##
###################################################################

CC := gcc:bin/gcc
MAKEDEPEND := gcc -MM -MF

INCPATH := -I SDK:MUI/C/Include -Iinclude -Imd4c/src -ISDK:include/include_h/jansson

CFLAGS := $(INCPATH)  -Werror -Wwrite-strings -Wextra  -DAMIGA=1 

ifeq ($(BUILD),release)
	CFLAGS += -O3
	APP = $(NAME)
else
	CFLAGS += -gstabs -D_DBUG=1
	APP = $(NAME).debug
endif


ifneq ($(MAKECMDGOALS), clean)
-include $(OBJS:.o=.d)
endif

.PHONY: clean init package all

all: $(DIR_OBJS)/$(APP)

$(DIR_OBJS)/$(APP): init $(OBJS)
	$(CC) -o $(DIR_OBJS)/$(APP) $(OBJS) $(LDFLAGS)
	copy $(DIR_OBJS)/$(APP) $(APP)

clean:
	rm -fr  $(DIR_OBJS)/
	
init:
	mkdir -p $(DIR_OBJS)


# Compile and generate dependency info
# 1. Compile the .c file
# 2. Generate dependency information, explicitly specifying the target name
$(DIR_OBJS)/%.o : %.c
	@echo ">>> c build for $@"
	$(CC) $(CFLAGS) $(CPPFLAGS) -o $@ -c $<
	@$(MAKEDEPEND) $(basename $@).d -MT $(basename $@).o $(CPPFLAGS) $(CFLAGS) $< 
	@mv -f $(basename $@).d $(basename $@).d.tmp
	@sed -e "s|.*:|$*.o:|" < $(basename $@).d.tmp > $(basename $@).d
	@mv -f $(basename $@).d $(basename $@).d.tmp
	@sed -e "s/.*://" -e "s/\\$$//" < $(basename $@).d.tmp | fmt -1 | \
		sed -e "s/^ *//" -e "s/$$/:/" >> $(basename $@).d
		@mv -f $(basename $@).d $(basename $@).d.tmp
	@rm -f $(basename $@).d.tmp   	
